# Generated by Django 4.2.13 on 2024-09-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='award',
            field=models.BooleanField(default=False),
        ),
    ]
